export let calendars = {
    "calendars": [
        {
            "id": "conor@hirehive.com",
            "calendarId": "conor@hirehive.com",
            "name": "conor@hirehive.com",
            "title": null,
            "start": null,
            "end": null,
            "category": null,
            "dueDateClass": null,
            "location": null,
            "attendees": null,
            "recurrenceRule": false,
            "isPending": false,
            "isFocused": false,
            "isVisible": true,
            "isReadOnly": false,
            "isPrivate": false,
            "isAllDay": false,
            "color": "#1d1d1d",
            "bgColor": "#9fe1e7",
            "dragBgColor": "#9fe1e7",
            "borderColor": "#1d1d1d",
            "customStyle": null,
            "accessRole": "owner",
            "eventsFetched": true,
            "type": "Google",
            "isOwner": true,
            "state": null,
            "$$hashKey": "object:338"
        },
        {
            "id": "hirehive.io_82rmud4vm6977mute9jve6rqao@group.calendar.google.com",
            "calendarId": "hirehive.io_82rmud4vm6977mute9jve6rqao@group.calendar.google.com",
            "name": "HireHive Team",
            "title": null,
            "start": null,
            "end": null,
            "category": null,
            "dueDateClass": null,
            "location": null,
            "attendees": null,
            "recurrenceRule": false,
            "isPending": false,
            "isFocused": false,
            "isVisible": true,
            "isReadOnly": false,
            "isPrivate": false,
            "isAllDay": false,
            "color": "#1d1d1d",
            "bgColor": "#cabdbf",
            "dragBgColor": "#cabdbf",
            "borderColor": "#1d1d1d",
            "customStyle": null,
            "accessRole": "writer",
            "eventsFetched": true,
            "type": "Google",
            "isOwner": true,
            "state": null,
            "$$hashKey": "object:339"
        },
        {
            "id": "Scheduled Interviews",
            "calendarId": "Scheduled Interviews",
            "name": "Scheduled Interviews",
            "title": null,
            "start": null,
            "end": null,
            "category": null,
            "dueDateClass": null,
            "location": null,
            "attendees": null,
            "recurrenceRule": false,
            "isPending": false,
            "isFocused": false,
            "isVisible": true,
            "isReadOnly": false,
            "isPrivate": false,
            "isAllDay": false,
            "color": "#000",
            "bgColor": "#FEF3C7",
            "dragBgColor": "#f5c400",
            "borderColor": "#f5c400",
            "customStyle": null,
            "accessRole": null,
            "eventsFetched": false,
            "type": "HireHive",
            "isOwner": false,
            "state": null,
            "$$hashKey": "object:342"
        }
    ],
    "events": [
        {
            "id": "23",
            "calendarId": "Scheduled Interviews",
            "name": null,
            "title": "Interview with Conor O Shea",
            "start": "2021-06-22T09:15:00Z",
            "end": "2021-06-22T10:00:00Z",
            "category": "time",
            "dueDateClass": null,
            "location": "cork",
            "attendees": [
                "conor o shea",
                "Test Admin"
            ],
            "recurrenceRule": false,
            "isPending": false,
            "isFocused": false,
            "isVisible": true,
            "isReadOnly": true,
            "isPrivate": false,
            "isAllDay": false,
            "color": "#000",
            "bgColor": "#FEF3C7",
            "dragBgColor": "#f5c400",
            "borderColor": "#f5c400",
            "customStyle": null,
            "accessRole": null,
            "eventsFetched": false,
            "type": null,
            "isOwner": false,
            "state": null
        },
        {
            "id": "24",
            "calendarId": "Scheduled Interviews",
            "name": null,
            "title": "Interview with Conor O Shea",
            "start": "2021-06-14T11:30:00Z",
            "end": "2021-06-14T12:00:00Z",
            "category": "time",
            "dueDateClass": null,
            "location": null,
            "attendees": [
                "conor o shea",
                "Test Admin"
            ],
            "recurrenceRule": false,
            "isPending": false,
            "isFocused": false,
            "isVisible": true,
            "isReadOnly": true,
            "isPrivate": false,
            "isAllDay": false,
            "color": "#000",
            "bgColor": "#FEF3C7",
            "dragBgColor": "#f5c400",
            "borderColor": "#f5c400",
            "customStyle": null,
            "accessRole": null,
            "eventsFetched": false,
            "type": null,
            "isOwner": false,
            "state": null
        },
        {
            "id": "1118up272u107frham9ni2t96s",
            "calendarId": "conor@hirehive.com",
            "name": null,
            "title": "Quarterly meeting & team dinner",
            "start": "2021-06-30T15:00:00Z",
            "end": "2021-06-30T19:30:00Z",
            "category": "time",
            "dueDateClass": null,
            "location": null,
            "attendees": [
                "noel@hirehive.com",
                "maelle@hirehive.com",
                "conor@hirehive.com"
            ],
            "recurrenceRule": false,
            "isPending": false,
            "isFocused": false,
            "isVisible": true,
            "isReadOnly": true,
            "isPrivate": false,
            "isAllDay": false,
            "color": "#000000",
            "bgColor": "#9fe1e7",
            "dragBgColor": "#000000",
            "borderColor": "#9fe1e7",
            "customStyle": null,
            "accessRole": null,
            "eventsFetched": false,
            "type": null,
            "isOwner": false,
            "state": null
        },
        {
            "id": "0gtsrc4k3tdqets99125556npe_20210729T100000Z",
            "calendarId": "conor@hirehive.com",
            "name": null,
            "title": "Monthly meeting & team lunch in RoW",
            "start": "2021-07-29T11:00:00Z",
            "end": "2021-07-29T14:30:00Z",
            "category": "time",
            "dueDateClass": null,
            "location": null,
            "attendees": [
                "noel@hirehive.com",
                "maelle@hirehive.com",
                "conor@hirehive.com"
            ],
            "recurrenceRule": false,
            "isPending": false,
            "isFocused": false,
            "isVisible": true,
            "isReadOnly": true,
            "isPrivate": false,
            "isAllDay": false,
            "color": "#000000",
            "bgColor": "#9fe1e7",
            "dragBgColor": "#000000",
            "borderColor": "#9fe1e7",
            "customStyle": null,
            "accessRole": null,
            "eventsFetched": false,
            "type": null,
            "isOwner": false,
            "state": null
        },
        {
            "id": "0bs88hbqcaul3sps2h8km8rvkk_20210610T090000Z",
            "calendarId": "conor@hirehive.com",
            "name": null,
            "title": "Tea & Chat",
            "start": "2021-06-10T10:00:00Z",
            "end": "2021-06-10T10:30:00Z",
            "category": "time",
            "dueDateClass": null,
            "location": "https://whereby.com/maelle-hirehive",
            "attendees": [
                "conor@hirehive.com",
                "noel@hirehive.com",
                "maelle@hirehive.com"
            ],
            "recurrenceRule": false,
            "isPending": false,
            "isFocused": false,
            "isVisible": true,
            "isReadOnly": true,
            "isPrivate": false,
            "isAllDay": false,
            "color": "#4a4a4a !important",
            "bgColor": "#ececec",
            "dragBgColor": "#4a4a4a !important",
            "borderColor": "#ececec",
            "customStyle": null,
            "accessRole": null,
            "eventsFetched": false,
            "type": null,
            "isOwner": false,
            "state": null
        },
        {
            "id": "0bs88hbqcaul3sps2h8km8rvkk_20210614T090000Z",
            "calendarId": "conor@hirehive.com",
            "name": null,
            "title": "Tea & Chat",
            "start": "2021-06-14T10:00:00Z",
            "end": "2021-06-14T10:30:00Z",
            "category": "time",
            "dueDateClass": null,
            "location": "https://whereby.com/maelle-hirehive",
            "attendees": [
                "conor@hirehive.com",
                "noel@hirehive.com",
                "maelle@hirehive.com"
            ],
            "recurrenceRule": false,
            "isPending": false,
            "isFocused": false,
            "isVisible": true,
            "isReadOnly": true,
            "isPrivate": false,
            "isAllDay": false,
            "color": "#4a4a4a !important",
            "bgColor": "#ececec",
            "dragBgColor": "#4a4a4a !important",
            "borderColor": "#ececec",
            "customStyle": null,
            "accessRole": null,
            "eventsFetched": false,
            "type": null,
            "isOwner": false,
            "state": null
        },
        {
            "id": "0bs88hbqcaul3sps2h8km8rvkk_20210617T090000Z",
            "calendarId": "conor@hirehive.com",
            "name": null,
            "title": "Tea & Chat",
            "start": "2021-06-17T10:00:00Z",
            "end": "2021-06-17T10:30:00Z",
            "category": "time",
            "dueDateClass": null,
            "location": "https://whereby.com/maelle-hirehive",
            "attendees": [
                "conor@hirehive.com",
                "noel@hirehive.com",
                "maelle@hirehive.com"
            ],
            "recurrenceRule": false,
            "isPending": false,
            "isFocused": false,
            "isVisible": true,
            "isReadOnly": true,
            "isPrivate": false,
            "isAllDay": false,
            "color": "#000000",
            "bgColor": "#9fe1e7",
            "dragBgColor": "#000000",
            "borderColor": "#9fe1e7",
            "customStyle": null,
            "accessRole": null,
            "eventsFetched": false,
            "type": null,
            "isOwner": false,
            "state": null
        },
        {
            "id": "0bs88hbqcaul3sps2h8km8rvkk_20210621T090000Z",
            "calendarId": "conor@hirehive.com",
            "name": null,
            "title": "Tea & Chat",
            "start": "2021-06-21T10:00:00Z",
            "end": "2021-06-21T10:30:00Z",
            "category": "time",
            "dueDateClass": null,
            "location": "https://whereby.com/maelle-hirehive",
            "attendees": [
                "conor@hirehive.com",
                "noel@hirehive.com",
                "maelle@hirehive.com"
            ],
            "recurrenceRule": false,
            "isPending": false,
            "isFocused": false,
            "isVisible": true,
            "isReadOnly": true,
            "isPrivate": false,
            "isAllDay": false,
            "color": "#000000",
            "bgColor": "#9fe1e7",
            "dragBgColor": "#000000",
            "borderColor": "#9fe1e7",
            "customStyle": null,
            "accessRole": null,
            "eventsFetched": false,
            "type": null,
            "isOwner": false,
            "state": null
        },
        {
            "id": "0bs88hbqcaul3sps2h8km8rvkk_20210624T090000Z",
            "calendarId": "conor@hirehive.com",
            "name": null,
            "title": "Tea & Chat",
            "start": "2021-06-24T10:00:00Z",
            "end": "2021-06-24T10:30:00Z",
            "category": "time",
            "dueDateClass": null,
            "location": "https://whereby.com/maelle-hirehive",
            "attendees": [
                "conor@hirehive.com",
                "noel@hirehive.com",
                "maelle@hirehive.com"
            ],
            "recurrenceRule": false,
            "isPending": false,
            "isFocused": false,
            "isVisible": true,
            "isReadOnly": true,
            "isPrivate": false,
            "isAllDay": false,
            "color": "#000000",
            "bgColor": "#9fe1e7",
            "dragBgColor": "#000000",
            "borderColor": "#9fe1e7",
            "customStyle": null,
            "accessRole": null,
            "eventsFetched": false,
            "type": null,
            "isOwner": false,
            "state": null
        },
        {
            "id": "0bs88hbqcaul3sps2h8km8rvkk_20210628T090000Z",
            "calendarId": "conor@hirehive.com",
            "name": null,
            "title": "Tea & Chat",
            "start": "2021-06-28T10:00:00Z",
            "end": "2021-06-28T10:30:00Z",
            "category": "time",
            "dueDateClass": null,
            "location": "https://whereby.com/maelle-hirehive",
            "attendees": [
                "conor@hirehive.com",
                "noel@hirehive.com",
                "maelle@hirehive.com"
            ],
            "recurrenceRule": false,
            "isPending": false,
            "isFocused": false,
            "isVisible": true,
            "isReadOnly": true,
            "isPrivate": false,
            "isAllDay": false,
            "color": "#000000",
            "bgColor": "#9fe1e7",
            "dragBgColor": "#000000",
            "borderColor": "#9fe1e7",
            "customStyle": null,
            "accessRole": null,
            "eventsFetched": false,
            "type": null,
            "isOwner": false,
            "state": null
        },
        {
            "id": "0bs88hbqcaul3sps2h8km8rvkk_20210701T090000Z",
            "calendarId": "conor@hirehive.com",
            "name": null,
            "title": "Tea & Chat",
            "start": "2021-07-01T10:00:00Z",
            "end": "2021-07-01T10:30:00Z",
            "category": "time",
            "dueDateClass": null,
            "location": "https://whereby.com/maelle-hirehive",
            "attendees": [
                "conor@hirehive.com",
                "noel@hirehive.com",
                "maelle@hirehive.com"
            ],
            "recurrenceRule": false,
            "isPending": false,
            "isFocused": false,
            "isVisible": true,
            "isReadOnly": true,
            "isPrivate": false,
            "isAllDay": false,
            "color": "#000000",
            "bgColor": "#9fe1e7",
            "dragBgColor": "#000000",
            "borderColor": "#9fe1e7",
            "customStyle": null,
            "accessRole": null,
            "eventsFetched": false,
            "type": null,
            "isOwner": false,
            "state": null
        },
        {
            "id": "0bs88hbqcaul3sps2h8km8rvkk_20210705T090000Z",
            "calendarId": "conor@hirehive.com",
            "name": null,
            "title": "Tea & Chat",
            "start": "2021-07-05T10:00:00Z",
            "end": "2021-07-05T10:30:00Z",
            "category": "time",
            "dueDateClass": null,
            "location": "https://whereby.com/maelle-hirehive",
            "attendees": [
                "conor@hirehive.com",
                "noel@hirehive.com",
                "maelle@hirehive.com"
            ],
            "recurrenceRule": false,
            "isPending": false,
            "isFocused": false,
            "isVisible": true,
            "isReadOnly": true,
            "isPrivate": false,
            "isAllDay": false,
            "color": "#000000",
            "bgColor": "#9fe1e7",
            "dragBgColor": "#000000",
            "borderColor": "#9fe1e7",
            "customStyle": null,
            "accessRole": null,
            "eventsFetched": false,
            "type": null,
            "isOwner": false,
            "state": null
        },
        {
            "id": "0bs88hbqcaul3sps2h8km8rvkk_20210708T090000Z",
            "calendarId": "conor@hirehive.com",
            "name": null,
            "title": "Tea & Chat",
            "start": "2021-07-08T10:00:00Z",
            "end": "2021-07-08T10:30:00Z",
            "category": "time",
            "dueDateClass": null,
            "location": "https://whereby.com/maelle-hirehive",
            "attendees": [
                "conor@hirehive.com",
                "noel@hirehive.com",
                "maelle@hirehive.com"
            ],
            "recurrenceRule": false,
            "isPending": false,
            "isFocused": false,
            "isVisible": true,
            "isReadOnly": true,
            "isPrivate": false,
            "isAllDay": false,
            "color": "#000000",
            "bgColor": "#9fe1e7",
            "dragBgColor": "#000000",
            "borderColor": "#9fe1e7",
            "customStyle": null,
            "accessRole": null,
            "eventsFetched": false,
            "type": null,
            "isOwner": false,
            "state": null
        },
        {
            "id": "0bs88hbqcaul3sps2h8km8rvkk_20210712T090000Z",
            "calendarId": "conor@hirehive.com",
            "name": null,
            "title": "Tea & Chat",
            "start": "2021-07-12T10:00:00Z",
            "end": "2021-07-12T10:30:00Z",
            "category": "time",
            "dueDateClass": null,
            "location": "https://whereby.com/maelle-hirehive",
            "attendees": [
                "conor@hirehive.com",
                "noel@hirehive.com",
                "maelle@hirehive.com"
            ],
            "recurrenceRule": false,
            "isPending": false,
            "isFocused": false,
            "isVisible": true,
            "isReadOnly": true,
            "isPrivate": false,
            "isAllDay": false,
            "color": "#000000",
            "bgColor": "#9fe1e7",
            "dragBgColor": "#000000",
            "borderColor": "#9fe1e7",
            "customStyle": null,
            "accessRole": null,
            "eventsFetched": false,
            "type": null,
            "isOwner": false,
            "state": null
        },
        {
            "id": "0bs88hbqcaul3sps2h8km8rvkk_20210715T090000Z",
            "calendarId": "conor@hirehive.com",
            "name": null,
            "title": "Tea & Chat",
            "start": "2021-07-15T10:00:00Z",
            "end": "2021-07-15T10:30:00Z",
            "category": "time",
            "dueDateClass": null,
            "location": "https://whereby.com/maelle-hirehive",
            "attendees": [
                "conor@hirehive.com",
                "noel@hirehive.com",
                "maelle@hirehive.com"
            ],
            "recurrenceRule": false,
            "isPending": false,
            "isFocused": false,
            "isVisible": true,
            "isReadOnly": true,
            "isPrivate": false,
            "isAllDay": false,
            "color": "#000000",
            "bgColor": "#9fe1e7",
            "dragBgColor": "#000000",
            "borderColor": "#9fe1e7",
            "customStyle": null,
            "accessRole": null,
            "eventsFetched": false,
            "type": null,
            "isOwner": false,
            "state": null
        },
        {
            "id": "0bs88hbqcaul3sps2h8km8rvkk_20210719T090000Z",
            "calendarId": "conor@hirehive.com",
            "name": null,
            "title": "Tea & Chat",
            "start": "2021-07-19T10:00:00Z",
            "end": "2021-07-19T10:30:00Z",
            "category": "time",
            "dueDateClass": null,
            "location": "https://whereby.com/maelle-hirehive",
            "attendees": [
                "conor@hirehive.com",
                "noel@hirehive.com",
                "maelle@hirehive.com"
            ],
            "recurrenceRule": false,
            "isPending": false,
            "isFocused": false,
            "isVisible": true,
            "isReadOnly": true,
            "isPrivate": false,
            "isAllDay": false,
            "color": "#000000",
            "bgColor": "#9fe1e7",
            "dragBgColor": "#000000",
            "borderColor": "#9fe1e7",
            "customStyle": null,
            "accessRole": null,
            "eventsFetched": false,
            "type": null,
            "isOwner": false,
            "state": null
        },
        {
            "id": "0bs88hbqcaul3sps2h8km8rvkk_20210722T090000Z",
            "calendarId": "conor@hirehive.com",
            "name": null,
            "title": "Tea & Chat",
            "start": "2021-07-22T10:00:00Z",
            "end": "2021-07-22T10:30:00Z",
            "category": "time",
            "dueDateClass": null,
            "location": "https://whereby.com/maelle-hirehive",
            "attendees": [
                "conor@hirehive.com",
                "noel@hirehive.com",
                "maelle@hirehive.com"
            ],
            "recurrenceRule": false,
            "isPending": false,
            "isFocused": false,
            "isVisible": true,
            "isReadOnly": true,
            "isPrivate": false,
            "isAllDay": false,
            "color": "#000000",
            "bgColor": "#9fe1e7",
            "dragBgColor": "#000000",
            "borderColor": "#9fe1e7",
            "customStyle": null,
            "accessRole": null,
            "eventsFetched": false,
            "type": null,
            "isOwner": false,
            "state": null
        },
        {
            "id": "0bs88hbqcaul3sps2h8km8rvkk_20210726T090000Z",
            "calendarId": "conor@hirehive.com",
            "name": null,
            "title": "Tea & Chat",
            "start": "2021-07-26T10:00:00Z",
            "end": "2021-07-26T10:30:00Z",
            "category": "time",
            "dueDateClass": null,
            "location": "https://whereby.com/maelle-hirehive",
            "attendees": [
                "conor@hirehive.com",
                "noel@hirehive.com",
                "maelle@hirehive.com"
            ],
            "recurrenceRule": false,
            "isPending": false,
            "isFocused": false,
            "isVisible": true,
            "isReadOnly": true,
            "isPrivate": false,
            "isAllDay": false,
            "color": "#000000",
            "bgColor": "#9fe1e7",
            "dragBgColor": "#000000",
            "borderColor": "#9fe1e7",
            "customStyle": null,
            "accessRole": null,
            "eventsFetched": false,
            "type": null,
            "isOwner": false,
            "state": null
        },
        {
            "id": "0bs88hbqcaul3sps2h8km8rvkk_20210729T090000Z",
            "calendarId": "conor@hirehive.com",
            "name": null,
            "title": "Tea & Chat",
            "start": "2021-07-29T10:00:00Z",
            "end": "2021-07-29T10:30:00Z",
            "category": "time",
            "dueDateClass": null,
            "location": "https://whereby.com/maelle-hirehive",
            "attendees": [
                "conor@hirehive.com",
                "noel@hirehive.com",
                "maelle@hirehive.com"
            ],
            "recurrenceRule": false,
            "isPending": false,
            "isFocused": false,
            "isVisible": true,
            "isReadOnly": true,
            "isPrivate": false,
            "isAllDay": false,
            "color": "#000000",
            "bgColor": "#9fe1e7",
            "dragBgColor": "#000000",
            "borderColor": "#9fe1e7",
            "customStyle": null,
            "accessRole": null,
            "eventsFetched": false,
            "type": null,
            "isOwner": false,
            "state": null
        },
        {
            "id": "0bs88hbqcaul3sps2h8km8rvkk_20210802T090000Z",
            "calendarId": "conor@hirehive.com",
            "name": null,
            "title": "Tea & Chat",
            "start": "2021-08-02T10:00:00Z",
            "end": "2021-08-02T10:30:00Z",
            "category": "time",
            "dueDateClass": null,
            "location": "https://whereby.com/maelle-hirehive",
            "attendees": [
                "conor@hirehive.com",
                "noel@hirehive.com",
                "maelle@hirehive.com"
            ],
            "recurrenceRule": false,
            "isPending": false,
            "isFocused": false,
            "isVisible": true,
            "isReadOnly": true,
            "isPrivate": false,
            "isAllDay": false,
            "color": "#000000",
            "bgColor": "#9fe1e7",
            "dragBgColor": "#000000",
            "borderColor": "#9fe1e7",
            "customStyle": null,
            "accessRole": null,
            "eventsFetched": false,
            "type": null,
            "isOwner": false,
            "state": null
        },
        {
            "id": "_d5n78pbiepkmatqvcko3adhgcgq3gohgccr66opk6h06gqbiclk6itj55phmur8",
            "calendarId": "conor@hirehive.com",
            "name": null,
            "title": "Interview with Conor O Shea",
            "start": "2021-06-22T10:15:00Z",
            "end": "2021-06-22T11:00:00Z",
            "category": "time",
            "dueDateClass": null,
            "location": " cork",
            "attendees": [
                "conor@hirehive.com"
            ],
            "recurrenceRule": false,
            "isPending": false,
            "isFocused": false,
            "isVisible": true,
            "isReadOnly": true,
            "isPrivate": false,
            "isAllDay": false,
            "color": "#000000",
            "bgColor": "#9fe1e7",
            "dragBgColor": "#000000",
            "borderColor": "#9fe1e7",
            "customStyle": null,
            "accessRole": null,
            "eventsFetched": false,
            "type": null,
            "isOwner": false,
            "state": null
        },
        {
            "id": "_d5n78pbiepkmatqv6gsj8d3468q3cor2cgpm2phhcl06gqbiclk6itj55phmur8",
            "calendarId": "conor@hirehive.com",
            "name": null,
            "title": "Interview with Conor O Shea",
            "start": "2021-06-14T12:30:00Z",
            "end": "2021-06-14T13:00:00Z",
            "category": "time",
            "dueDateClass": null,
            "location": null,
            "attendees": [
                "conor@hirehive.com"
            ],
            "recurrenceRule": false,
            "isPending": false,
            "isFocused": false,
            "isVisible": true,
            "isReadOnly": true,
            "isPrivate": false,
            "isAllDay": false,
            "color": "#4a4a4a !important",
            "bgColor": "#ececec",
            "dragBgColor": "#4a4a4a !important",
            "borderColor": "#ececec",
            "customStyle": null,
            "accessRole": null,
            "eventsFetched": false,
            "type": null,
            "isOwner": false,
            "state": null
        },
        {
            "id": "_d5n78pbiepkmatqv6op34cpjccsj8dphc8o6cpb4c906gqbiclk6itj55phmur8",
            "calendarId": "conor@hirehive.com",
            "name": null,
            "title": "Interview with Conor O Shea5",
            "start": "2021-06-14T15:30:00Z",
            "end": "2021-06-14T16:00:00Z",
            "category": "time",
            "dueDateClass": null,
            "location": null,
            "attendees": [
                "conor@hirehive.com",
                "Conor o shea5"
            ],
            "recurrenceRule": false,
            "isPending": false,
            "isFocused": false,
            "isVisible": true,
            "isReadOnly": true,
            "isPrivate": false,
            "isAllDay": false,
            "color": "#4a4a4a !important",
            "bgColor": "#ececec",
            "dragBgColor": "#4a4a4a !important",
            "borderColor": "#ececec",
            "customStyle": null,
            "accessRole": null,
            "eventsFetched": false,
            "type": null,
            "isOwner": false,
            "state": null
        },
        {
            "id": "0bs88hbqcaul3sps2h8km8rvkk_20210610T090000Z",
            "calendarId": "hirehive.io_82rmud4vm6977mute9jve6rqao@group.calendar.google.com",
            "name": null,
            "title": "Tea & Chat",
            "start": "2021-06-10T10:00:00Z",
            "end": "2021-06-10T10:30:00Z",
            "category": "time",
            "dueDateClass": null,
            "location": "https://whereby.com/maelle-hirehive",
            "attendees": [
                "conor@hirehive.com",
                "noel@hirehive.com",
                "maelle@hirehive.com"
            ],
            "recurrenceRule": false,
            "isPending": false,
            "isFocused": false,
            "isVisible": true,
            "isReadOnly": true,
            "isPrivate": false,
            "isAllDay": false,
            "color": "#4a4a4a !important",
            "bgColor": "#ececec",
            "dragBgColor": "#4a4a4a !important",
            "borderColor": "#ececec",
            "customStyle": null,
            "accessRole": null,
            "eventsFetched": false,
            "type": null,
            "isOwner": false,
            "state": null
        },
        {
            "id": "0bs88hbqcaul3sps2h8km8rvkk_20210614T090000Z",
            "calendarId": "hirehive.io_82rmud4vm6977mute9jve6rqao@group.calendar.google.com",
            "name": null,
            "title": "Tea & Chat",
            "start": "2021-06-14T10:00:00Z",
            "end": "2021-06-14T10:30:00Z",
            "category": "time",
            "dueDateClass": null,
            "location": "https://whereby.com/maelle-hirehive",
            "attendees": [
                "conor@hirehive.com",
                "noel@hirehive.com",
                "maelle@hirehive.com"
            ],
            "recurrenceRule": false,
            "isPending": false,
            "isFocused": false,
            "isVisible": true,
            "isReadOnly": true,
            "isPrivate": false,
            "isAllDay": false,
            "color": "#4a4a4a !important",
            "bgColor": "#ececec",
            "dragBgColor": "#4a4a4a !important",
            "borderColor": "#ececec",
            "customStyle": null,
            "accessRole": null,
            "eventsFetched": false,
            "type": null,
            "isOwner": false,
            "state": null
        },
        {
            "id": "0bs88hbqcaul3sps2h8km8rvkk_20210617T090000Z",
            "calendarId": "hirehive.io_82rmud4vm6977mute9jve6rqao@group.calendar.google.com",
            "name": null,
            "title": "Tea & Chat",
            "start": "2021-06-17T10:00:00Z",
            "end": "2021-06-17T10:30:00Z",
            "category": "time",
            "dueDateClass": null,
            "location": "https://whereby.com/maelle-hirehive",
            "attendees": [
                "conor@hirehive.com",
                "noel@hirehive.com",
                "maelle@hirehive.com"
            ],
            "recurrenceRule": false,
            "isPending": false,
            "isFocused": false,
            "isVisible": true,
            "isReadOnly": true,
            "isPrivate": false,
            "isAllDay": false,
            "color": "#000000",
            "bgColor": "#cabdbf",
            "dragBgColor": "#000000",
            "borderColor": "#cabdbf",
            "customStyle": null,
            "accessRole": null,
            "eventsFetched": false,
            "type": null,
            "isOwner": false,
            "state": null
        },
        {
            "id": "0bs88hbqcaul3sps2h8km8rvkk_20210621T090000Z",
            "calendarId": "hirehive.io_82rmud4vm6977mute9jve6rqao@group.calendar.google.com",
            "name": null,
            "title": "Tea & Chat",
            "start": "2021-06-21T10:00:00Z",
            "end": "2021-06-21T10:30:00Z",
            "category": "time",
            "dueDateClass": null,
            "location": "https://whereby.com/maelle-hirehive",
            "attendees": [
                "conor@hirehive.com",
                "noel@hirehive.com",
                "maelle@hirehive.com"
            ],
            "recurrenceRule": false,
            "isPending": false,
            "isFocused": false,
            "isVisible": true,
            "isReadOnly": true,
            "isPrivate": false,
            "isAllDay": false,
            "color": "#000000",
            "bgColor": "#cabdbf",
            "dragBgColor": "#000000",
            "borderColor": "#cabdbf",
            "customStyle": null,
            "accessRole": null,
            "eventsFetched": false,
            "type": null,
            "isOwner": false,
            "state": null
        },
        {
            "id": "0bs88hbqcaul3sps2h8km8rvkk_20210624T090000Z",
            "calendarId": "hirehive.io_82rmud4vm6977mute9jve6rqao@group.calendar.google.com",
            "name": null,
            "title": "Tea & Chat",
            "start": "2021-06-24T10:00:00Z",
            "end": "2021-06-24T10:30:00Z",
            "category": "time",
            "dueDateClass": null,
            "location": "https://whereby.com/maelle-hirehive",
            "attendees": [
                "conor@hirehive.com",
                "noel@hirehive.com",
                "maelle@hirehive.com"
            ],
            "recurrenceRule": false,
            "isPending": false,
            "isFocused": false,
            "isVisible": true,
            "isReadOnly": true,
            "isPrivate": false,
            "isAllDay": false,
            "color": "#000000",
            "bgColor": "#cabdbf",
            "dragBgColor": "#000000",
            "borderColor": "#cabdbf",
            "customStyle": null,
            "accessRole": null,
            "eventsFetched": false,
            "type": null,
            "isOwner": false,
            "state": null
        },
        {
            "id": "0bs88hbqcaul3sps2h8km8rvkk_20210628T090000Z",
            "calendarId": "hirehive.io_82rmud4vm6977mute9jve6rqao@group.calendar.google.com",
            "name": null,
            "title": "Tea & Chat",
            "start": "2021-06-28T10:00:00Z",
            "end": "2021-06-28T10:30:00Z",
            "category": "time",
            "dueDateClass": null,
            "location": "https://whereby.com/maelle-hirehive",
            "attendees": [
                "conor@hirehive.com",
                "noel@hirehive.com",
                "maelle@hirehive.com"
            ],
            "recurrenceRule": false,
            "isPending": false,
            "isFocused": false,
            "isVisible": true,
            "isReadOnly": true,
            "isPrivate": false,
            "isAllDay": false,
            "color": "#000000",
            "bgColor": "#cabdbf",
            "dragBgColor": "#000000",
            "borderColor": "#cabdbf",
            "customStyle": null,
            "accessRole": null,
            "eventsFetched": false,
            "type": null,
            "isOwner": false,
            "state": null
        },
        {
            "id": "0bs88hbqcaul3sps2h8km8rvkk_20210701T090000Z",
            "calendarId": "hirehive.io_82rmud4vm6977mute9jve6rqao@group.calendar.google.com",
            "name": null,
            "title": "Tea & Chat",
            "start": "2021-07-01T10:00:00Z",
            "end": "2021-07-01T10:30:00Z",
            "category": "time",
            "dueDateClass": null,
            "location": "https://whereby.com/maelle-hirehive",
            "attendees": [
                "conor@hirehive.com",
                "noel@hirehive.com",
                "maelle@hirehive.com"
            ],
            "recurrenceRule": false,
            "isPending": false,
            "isFocused": false,
            "isVisible": true,
            "isReadOnly": true,
            "isPrivate": false,
            "isAllDay": false,
            "color": "#000000",
            "bgColor": "#cabdbf",
            "dragBgColor": "#000000",
            "borderColor": "#cabdbf",
            "customStyle": null,
            "accessRole": null,
            "eventsFetched": false,
            "type": null,
            "isOwner": false,
            "state": null
        },
        {
            "id": "0bs88hbqcaul3sps2h8km8rvkk_20210705T090000Z",
            "calendarId": "hirehive.io_82rmud4vm6977mute9jve6rqao@group.calendar.google.com",
            "name": null,
            "title": "Tea & Chat",
            "start": "2021-07-05T10:00:00Z",
            "end": "2021-07-05T10:30:00Z",
            "category": "time",
            "dueDateClass": null,
            "location": "https://whereby.com/maelle-hirehive",
            "attendees": [
                "conor@hirehive.com",
                "noel@hirehive.com",
                "maelle@hirehive.com"
            ],
            "recurrenceRule": false,
            "isPending": false,
            "isFocused": false,
            "isVisible": true,
            "isReadOnly": true,
            "isPrivate": false,
            "isAllDay": false,
            "color": "#000000",
            "bgColor": "#cabdbf",
            "dragBgColor": "#000000",
            "borderColor": "#cabdbf",
            "customStyle": null,
            "accessRole": null,
            "eventsFetched": false,
            "type": null,
            "isOwner": false,
            "state": null
        },
        {
            "id": "0bs88hbqcaul3sps2h8km8rvkk_20210708T090000Z",
            "calendarId": "hirehive.io_82rmud4vm6977mute9jve6rqao@group.calendar.google.com",
            "name": null,
            "title": "Tea & Chat",
            "start": "2021-07-08T10:00:00Z",
            "end": "2021-07-08T10:30:00Z",
            "category": "time",
            "dueDateClass": null,
            "location": "https://whereby.com/maelle-hirehive",
            "attendees": [
                "conor@hirehive.com",
                "noel@hirehive.com",
                "maelle@hirehive.com"
            ],
            "recurrenceRule": false,
            "isPending": false,
            "isFocused": false,
            "isVisible": true,
            "isReadOnly": true,
            "isPrivate": false,
            "isAllDay": false,
            "color": "#000000",
            "bgColor": "#cabdbf",
            "dragBgColor": "#000000",
            "borderColor": "#cabdbf",
            "customStyle": null,
            "accessRole": null,
            "eventsFetched": false,
            "type": null,
            "isOwner": false,
            "state": null
        },
        {
            "id": "0bs88hbqcaul3sps2h8km8rvkk_20210712T090000Z",
            "calendarId": "hirehive.io_82rmud4vm6977mute9jve6rqao@group.calendar.google.com",
            "name": null,
            "title": "Tea & Chat",
            "start": "2021-07-12T10:00:00Z",
            "end": "2021-07-12T10:30:00Z",
            "category": "time",
            "dueDateClass": null,
            "location": "https://whereby.com/maelle-hirehive",
            "attendees": [
                "conor@hirehive.com",
                "noel@hirehive.com",
                "maelle@hirehive.com"
            ],
            "recurrenceRule": false,
            "isPending": false,
            "isFocused": false,
            "isVisible": true,
            "isReadOnly": true,
            "isPrivate": false,
            "isAllDay": false,
            "color": "#000000",
            "bgColor": "#cabdbf",
            "dragBgColor": "#000000",
            "borderColor": "#cabdbf",
            "customStyle": null,
            "accessRole": null,
            "eventsFetched": false,
            "type": null,
            "isOwner": false,
            "state": null
        },
        {
            "id": "0bs88hbqcaul3sps2h8km8rvkk_20210715T090000Z",
            "calendarId": "hirehive.io_82rmud4vm6977mute9jve6rqao@group.calendar.google.com",
            "name": null,
            "title": "Tea & Chat",
            "start": "2021-07-15T10:00:00Z",
            "end": "2021-07-15T10:30:00Z",
            "category": "time",
            "dueDateClass": null,
            "location": "https://whereby.com/maelle-hirehive",
            "attendees": [
                "conor@hirehive.com",
                "noel@hirehive.com",
                "maelle@hirehive.com"
            ],
            "recurrenceRule": false,
            "isPending": false,
            "isFocused": false,
            "isVisible": true,
            "isReadOnly": true,
            "isPrivate": false,
            "isAllDay": false,
            "color": "#000000",
            "bgColor": "#cabdbf",
            "dragBgColor": "#000000",
            "borderColor": "#cabdbf",
            "customStyle": null,
            "accessRole": null,
            "eventsFetched": false,
            "type": null,
            "isOwner": false,
            "state": null
        },
        {
            "id": "0bs88hbqcaul3sps2h8km8rvkk_20210719T090000Z",
            "calendarId": "hirehive.io_82rmud4vm6977mute9jve6rqao@group.calendar.google.com",
            "name": null,
            "title": "Tea & Chat",
            "start": "2021-07-19T10:00:00Z",
            "end": "2021-07-19T10:30:00Z",
            "category": "time",
            "dueDateClass": null,
            "location": "https://whereby.com/maelle-hirehive",
            "attendees": [
                "conor@hirehive.com",
                "noel@hirehive.com",
                "maelle@hirehive.com"
            ],
            "recurrenceRule": false,
            "isPending": false,
            "isFocused": false,
            "isVisible": true,
            "isReadOnly": true,
            "isPrivate": false,
            "isAllDay": false,
            "color": "#000000",
            "bgColor": "#cabdbf",
            "dragBgColor": "#000000",
            "borderColor": "#cabdbf",
            "customStyle": null,
            "accessRole": null,
            "eventsFetched": false,
            "type": null,
            "isOwner": false,
            "state": null
        },
        {
            "id": "0bs88hbqcaul3sps2h8km8rvkk_20210722T090000Z",
            "calendarId": "hirehive.io_82rmud4vm6977mute9jve6rqao@group.calendar.google.com",
            "name": null,
            "title": "Tea & Chat",
            "start": "2021-07-22T10:00:00Z",
            "end": "2021-07-22T10:30:00Z",
            "category": "time",
            "dueDateClass": null,
            "location": "https://whereby.com/maelle-hirehive",
            "attendees": [
                "conor@hirehive.com",
                "noel@hirehive.com",
                "maelle@hirehive.com"
            ],
            "recurrenceRule": false,
            "isPending": false,
            "isFocused": false,
            "isVisible": true,
            "isReadOnly": true,
            "isPrivate": false,
            "isAllDay": false,
            "color": "#000000",
            "bgColor": "#cabdbf",
            "dragBgColor": "#000000",
            "borderColor": "#cabdbf",
            "customStyle": null,
            "accessRole": null,
            "eventsFetched": false,
            "type": null,
            "isOwner": false,
            "state": null
        },
        {
            "id": "0bs88hbqcaul3sps2h8km8rvkk_20210726T090000Z",
            "calendarId": "hirehive.io_82rmud4vm6977mute9jve6rqao@group.calendar.google.com",
            "name": null,
            "title": "Tea & Chat",
            "start": "2021-07-26T10:00:00Z",
            "end": "2021-07-26T10:30:00Z",
            "category": "time",
            "dueDateClass": null,
            "location": "https://whereby.com/maelle-hirehive",
            "attendees": [
                "conor@hirehive.com",
                "noel@hirehive.com",
                "maelle@hirehive.com"
            ],
            "recurrenceRule": false,
            "isPending": false,
            "isFocused": false,
            "isVisible": true,
            "isReadOnly": true,
            "isPrivate": false,
            "isAllDay": false,
            "color": "#000000",
            "bgColor": "#cabdbf",
            "dragBgColor": "#000000",
            "borderColor": "#cabdbf",
            "customStyle": null,
            "accessRole": null,
            "eventsFetched": false,
            "type": null,
            "isOwner": false,
            "state": null
        },
        {
            "id": "0bs88hbqcaul3sps2h8km8rvkk_20210729T090000Z",
            "calendarId": "hirehive.io_82rmud4vm6977mute9jve6rqao@group.calendar.google.com",
            "name": null,
            "title": "Tea & Chat",
            "start": "2021-07-29T10:00:00Z",
            "end": "2021-07-29T10:30:00Z",
            "category": "time",
            "dueDateClass": null,
            "location": "https://whereby.com/maelle-hirehive",
            "attendees": [
                "conor@hirehive.com",
                "noel@hirehive.com",
                "maelle@hirehive.com"
            ],
            "recurrenceRule": false,
            "isPending": false,
            "isFocused": false,
            "isVisible": true,
            "isReadOnly": true,
            "isPrivate": false,
            "isAllDay": false,
            "color": "#000000",
            "bgColor": "#cabdbf",
            "dragBgColor": "#000000",
            "borderColor": "#cabdbf",
            "customStyle": null,
            "accessRole": null,
            "eventsFetched": false,
            "type": null,
            "isOwner": false,
            "state": null
        },
        {
            "id": "0bs88hbqcaul3sps2h8km8rvkk_20210802T090000Z",
            "calendarId": "hirehive.io_82rmud4vm6977mute9jve6rqao@group.calendar.google.com",
            "name": null,
            "title": "Tea & Chat",
            "start": "2021-08-02T10:00:00Z",
            "end": "2021-08-02T10:30:00Z",
            "category": "time",
            "dueDateClass": null,
            "location": "https://whereby.com/maelle-hirehive",
            "attendees": [
                "conor@hirehive.com",
                "noel@hirehive.com",
                "maelle@hirehive.com"
            ],
            "recurrenceRule": false,
            "isPending": false,
            "isFocused": false,
            "isVisible": true,
            "isReadOnly": true,
            "isPrivate": false,
            "isAllDay": false,
            "color": "#000000",
            "bgColor": "#cabdbf",
            "dragBgColor": "#000000",
            "borderColor": "#cabdbf",
            "customStyle": null,
            "accessRole": null,
            "eventsFetched": false,
            "type": null,
            "isOwner": false,
            "state": null
        },
        {
            "id": "70o49kfjkbtbgnp4vafe5ku92b",
            "calendarId": "hirehive.io_82rmud4vm6977mute9jve6rqao@group.calendar.google.com",
            "name": null,
            "title": "Marie's joining HH!",
            "start": "2021-07-08",
            "end": "2021-07-08T22:59:59.000Z",
            "category": "allday",
            "dueDateClass": null,
            "location": null,
            "attendees": [],
            "recurrenceRule": false,
            "isPending": false,
            "isFocused": false,
            "isVisible": true,
            "isReadOnly": true,
            "isPrivate": false,
            "isAllDay": true,
            "color": "#000000",
            "bgColor": "#cabdbf",
            "dragBgColor": "#000000",
            "borderColor": "#cabdbf",
            "customStyle": null,
            "accessRole": null,
            "eventsFetched": false,
            "type": null,
            "isOwner": false,
            "state": null
        }
    ]
}